# Generated by Django 4.2.5 on 2023-09-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_like_num_remove_post_like_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
