# Generated by Django 4.2.5 on 2023-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('google', 'google'), ('kakao', 'kakao')], default='email', max_length=6),
        ),
    ]
