# Generated by Django 4.2.5 on 2023-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='63acBIqI6m', max_length=10),
        ),
    ]
