# Generated by Django 4.2.5 on 2023-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
