# Generated by Django 4.2.5 on 2023-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_login_method_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('home ', 'home'), ('google', 'google')], default='home ', max_length=8),
        ),
    ]
